name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  enviroment-check:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checking sync script
        run: |
          source dev-utils/sync.sh
          which python3
          if [[ "$(which python3)" == *"venv/bin/python3"* ]]; then
            echo "Running in venv"
          else
            echo "::error:: Not running in venv"
            exit 1
          fi
